    <?php include 'cabecera.php'; ?>
      <section class="parallax-container" data-parallax-img="images/pexels-cottonbro-4098369.jpg">
        <div class="parallax-content breadcrumbs-custom context-dark">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-12 col-lg-9">
                <h2 class="breadcrumbs-custom-title">Que tratamos</h2>
                <ul class="breadcrumbs-custom-path">

                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>

       <br> <br>

            <div class="col-xl-12">
              <ul class="list-xxl heading-list">
                <li>
                  <h3>Ansiedad</h3>
                  <p>La ansiedad y el miedo son experiencias normales que todos experimentamos cada cierto tiempo. El miedo surge ante una amenaza externa identificable (por ejemplo, ante un atraco) y es una de las seis emociones básicas. El miedo se considera fundamental para la supervivencia porque nos prepara para la reacción de lucha-huida ante situaciones de riesgo inminente. Por otra parte, la ansiedad es un estado emocional no placentero que se acompaña de nerviosismo y una sensación de desasosiego. Habitualmente, el miedo aparece en el mismo momento en el que se nos presenta el peligro (por ejemplo, al encontrarnos un oso en el bosque). Mientras que, la ansiedad puede aparecer al imaginar el peligro (ansiedad anticipatoria), tras desaparecer la amenaza o sin causa aparente. Tanto la ansiedad como el miedo se suelen acompañar de cambios físicos y conductuales. Un cierto grado de ansiedad en determinadas circunstancias es necesario. Por ejemplo, estar un poco nervioso al enfrentarnos a un examen va a permitir que podamos concentrarnos mejor en la tarea y estemos motivados en hacerlo bien. Sin embargo, cuando la ansiedad supera un determinado umbral o se mantiene un tiempo muy prolongado, deja de considerarse adaptativa. Esta situación es la que marca el comienzo de un Trastorno de ansiedad, porque empieza a provocar angustia excesiva, malestar significativo y un empeoramiento en el rendimiento. Algunas personas tienen más tolerancia a la ansiedad que otras, pero todas pueden desarrollar un Trastorno de ansiedad. Para poder delimitar la línea que separa la ansiedad adaptativa del Trastorno de ansiedad debemos fijarnos en: la experiencia subjetiva del paciente, la interferencia con el día a día, la persistencia en el tiempo y la intensidad de los síntomas. </p>
                </li>
                <li>
                  <h3>La depresión</h3>
                  <p>La depresión es una enfermedad muy frecuente que afecta a más de 300 millones de personas de todo el mundo, según la Organización Mundial de la Salud (OMS). Se estima que una de cada cinco personas la sufrirán a lo largo de sus vidas, afectando al doble de mujeres que hombres. La depresión, en los casos más graves, puede conducir al suicidio, ya que multiplica por 20 el riesgo de suicidio consumado. Además de ser una enfermedad muy frecuente y potencialmente letal, es la principal causa mundial de discapacidad, por delante de las enfermedades cardiovasculares y del cáncer. La depresión es una de las enfermedades más frecuentes en el ser humano, sobre todo en la mujer. No solo afecta a muchas personas, sino que también es una enfermedad crónica que tiende a aparecer recurrentemente en forma de episodios. Esto hace que sea considerada la primera causa mundial de discapacidad, tanto en mujeres como en varones, por delante de las enfermedades cardiovasculares y del cáncer. Se estima que 3000 personas se suicidan cada día en el mundo como consecuencia de la depresión que sufren. Esto supone no solo la pérdida de la vida para la persona que se suicida, sino también una importante carga emocional para sus familiares y allegados.</p>
                </li>
                <li>
                  <h3>Insomnio</h3>
                  <p>El insomnio es el trastorno del sueño más habitual, y se caracteriza por la percepción subjetiva de un sueño insatisfactorio, tanto en duración como en capacidad reparadora, que, además, produce una interferencia durante la vigilia, influyendo negativamente en la calidad de vida. Afecta con mayor frecuencia a mujeres adultas, aunque cada vez es más frecuente en hombres y en población infantil. A pesar de lo importante que es el sueño en la vida de una persona, y que dedicamos de media un tercio de nuestra vida a dormir, la mayoría de las personas saben poco tanto del sueño como del insomnio. El proceso por el que pasamos de la vigilia al sueño es tan complejo que definir el insomnio se hace igual de difícil. Por lo tanto, lo más sencillo es definirlo desde la experiencia subjetiva de quien lo padece. </p>
                </li>
                <li>
                  <h3>Estrés postraumático</h3>
                  <p>El Trastorno de estrés postraumático (TEPT) es una posible consecuencia psicológica y conductual de la exposición a un acontecimiento traumático. Puede ocurrir en personas de todas las edades y es más frecuente en mujeres que en hombres. Aparecen cuatro síntomas predominantes: reexperimentación del acontecimiento traumático, evitación de estímulos relacionados con el trauma, embotamiento mental y un estado de hiperactivación. El tratamiento de este trastorno corresponde a los psiquiatras y psicólogos clínicos. En el año 1982 se publicó la tercera edición del DSM (Manual de diagnóstico de los trastornos mentales) y por primera vez se reconoció que las secuelas que podían quedar tras la exposición a un suceso traumático podían configurar un trastorno mental. Se denominó Trastorno de estrés postraumático, conocido también por las siglas en español (TEPT) y en inglés (PTSD).</p>
                </li>
                <li>
                  <h3>Ataque o crisis de ansiedad</h3>
                  <p>Las crisis de ansiedad son estados de extrema ansiedad de breve duración y rápida instauración que se acompañan de síntomas físicos, como sensación de falta de aire, palpitaciones, presión en el pecho, mareo y miedo a perder el control o a morir. El tratamiento, tanto psicológico como farmacológico, ofrece magníficos resultados y evita que se complique con otros trastornos de ansiedad, como la Agorafobia o el Trastorno de ansiedad generalizada. Eventualmente, no tratarlas durante mucho tiempo puede llevar a la Depresión mayor o al consumo de sustancias. El término ataque de ansiedad es intercambiable por crisis de ansiedad, crisis de pánico y crisis de angustia. Un ataque de ansiedad es una avalancha súbita de miedo o malestar intensos que en pocos minutos alcanza su máxima intensidad. El malestar consiste en una serie de síntomas físicos que pueden ser muy variables junto con una intensa sensación de ansiedad. Para que entendamos la magnitud del malestar, durante el apogeo de la crisis de ansiedad, muchas personas creen estar sufriendo un ataque al corazón. Puede surgir desde un estado de calma o desde un estado de ansiedad y su duración es de 10 a 45 minutos desde que alcanza su máxima intensidad. Al finalizar la crisis, la persona puede regresar al estado de previo de calma o ansiedad; mientras que, en otros casos, se mantiene un nivel moderado de ansiedad hasta incluso podría repetirse la crisis más adelante.</p>
                </li>
                <li>
                  <h3>Agorafobia</h3>
                  <p>La Agorafobia es la fobia más frecuente y también la más incapacitante. Consiste en la aparición de ansiedad y miedo a un elevado número de situaciones de las que pueda ser difícil escapar o donde pedir ayuda sea difícil o embarazoso. Aparece una sensación de catástrofe inminente que suele acompañarse de una crisis de ansiedad. El miedo y la ansiedad anticipatoria puede recluir al paciente en su casa en un intento de sentirse a salvo y evitar las situaciones agorafóbicas, que pueden ser múltiples. Este trastorno es más frecuente en mujeres y suele aparecer entre los 20 y los 30 años. Tiende a la cronicidad y necesita tratamiento para resolverse y evitar complicaciones secundarias. La Agorafobia se caracteriza por un intenso y desproporcionado temor al exponerse o anticipar un elevado número de situaciones. Las situaciones que desencadenan el miedo son aquellas de las que pueda resultar complicado escapar o en las que las que pedir ayuda puede resultar difícil o embarazoso. El paciente con agorafobia va a evitar estas situaciones por la intensa ansiedad que le provoca incluso el pensar en ellas. Normalmente, la elevada ansiedad va a acompañada de la sensación subjetiva de que algo terrible va a suceder.La Agorafobia es la más frecuente de todas las fobias, llegando a suponer el 60 % de ellas. Cada año, aproximadamente un 1,7 % de adultos y adolescentes son diagnosticados de Agorafobia. Es el doble de frecuente en mujeres. La época de la vida más habitual es la adolescencia y el comienzo de la edad adulta. En dos tercios de todos los casos, los primeros síntomas aparecen antes de los 35 años. </p>
                </li>
                <li>
                  <h3>Ansiedad generalizada</h3>
                  <p>El Trastorno de ansiedad generalizada (conocido con las siglas TAG) se caracteriza por ansiedad y preocupación excesiva acerca de múltiples acontecimientos o actividades. A esta preocupación la llamamos anticipación aprensiva porque consiste en anticipar supuestos acontecimientos adversos que tienen una baja o muy baja probabilidad de ocurrir. Además, la intensidad de la preocupación es desproporcionada al impacto real del supuesto suceso o a la probabilidad de que ocurra. Sin embargo, la persona no es capaz de controlar dicha preocupación y el pensar en ella le interfiere en la realización de otras tareas inmediatas. Las personas con ansiedad generalizada experimentan una ansiedad persistente y preocupación desproporcionada a la situación o acontecimiento real. Típicamente, suelen preocuparse por acontecimientos rutinarios de la vida, como llegar tarde a una clase extraescolar de sus hijos, tener que bajar a comprar aceite porque se ha terminado, pagar una multa de aparcamiento, no tener tiempo de terminar todas las tareas domésticas, etc. Estas preocupaciones suelen variar con el tiempo: los niños se preocupan por si hacen bien las tareas de clase, los adolescentes se preocupan por los exámenes, los adultos por la situación económica familiar y los ancianos por la salud de sus familiares. </p>
                </li>
                <li>
                  <h3>TOC</h3>
                  <p>TOC es el acrónimo de Trastorno obsesivo compulsivo. Se trata de una enfermedad relativamente común que afecta a un 1,5 % de la población infantil y adulta. Se caracteriza por la presencia de obsesiones y compulsiones, habitualmente ambas. El Trastorno obsesivo compulsivo se caracteriza por la presencia de obsesiones y compulsiones de forma recurrente. Estos síntomas deben ser lo suficientemente graves como para producir un malestar significativo, una excesiva pérdida de tiempo y un deterioro de la rutina general. Las personas con TOC, por lo general, suelen dedicar varias horas al día al pensamiento obsesivo y a realizar las compulsiones que lo calman. Esta dedicación y malestar generados suele provocar también un deterioro llamativo en la actividad cotidiana. La vida social se puede ver reducida, así como el rendimiento laboral y la confianza en uno mismo. En algunos momentos, el paciente llega a ser capaz de reconocer que lo que le ocurre es excesivo o irracional.</p>
                </li>
                <li>
                  <h3>Fobia social</h3>
                  <p>La fobia social o trastorno de ansiedad social es una de las enfermedades más frecuentes en salud mental. Suele comenzar en la infancia o adolescencia. Potencialmente puede provocar un importante sufrimiento y discapacidad en logros académicos, oportunidades de empleo, independencia económica y la consecución de relaciones sociales, laborales y de intimidad. Tiene una evolución hacia la cronicidad y suele terminar provocando otros problemas, como depresión y abuso de alcohol. El trastorno de ansiedad social se define por un temor persistente e intenso o ansiedad a las situaciones sociales en las que la persona se pueda sentir analizada por los demás. La vergüenza, el temor por sentirse humillado y el temor por la evaluación negativa de otras personas se convierte en la mayor de las preocupaciones, provocando una limitación significativa en el funcionamiento cotidiano y afectando muy negativamente a su calidad de vida. En algunos casos se convierte en una enfermedad crónica y debilitante.La exposición a situaciones sociales provoca el temor a ser evaluado negativamente por los demás. El paciente teme ser juzgado por otras personas. Teme que lo consideren ansioso, débil, intimidante, sucio, desagradable o loco. Teme también actuar o mostrarse de una determinada manera en la que pueda él creer que hace pensar a los demás algo negativo de él. Teme manifestar ante los demás síntomas que puedan ser evaluados negativamente, como: ruborizarse, sudar, tartamudear, oler mal o evitar el contacto ocular.</p>
                </li>
                <li>
                  <h3>Trastorno de personalidad</h3>
                  <p>Existen distintos tipos de trastornos de personalidad en función de los rasgos desadaptativos que se expresen. Las personas con trastorno de personalidad van a tener serias dificultades para adaptarse a los cambios del entorno debido a su inflexibilidad adaptativa y a la repetición patológica de patrones de comportamiento y emocionales desadaptativos. A continuación vamos a ver qué significa todo esto, después de explicar qué es la personalidad y cómo es una “personalidad normal”. Por último, abordaremos el tratamiento del trastorno de personalidad.La personalidad es lo que nos diferencia de los demás, pero también es lo que nos hace únicos. A las personas con una cualidad distintiva, le decimos que tiene “mucha personalidad” o que “tiene carácter”. Decimos de algunas personas que “no tienen personalidad” cuando les cuesta tomar decisiones o no se posicionan ante un problema. También hablamos de “personas con buen carácter” y “personas con mal carácter”.</p>
                </li>
                <li>
                  <h3>Adicciones</h3>
                  <p>En mente A mente entendemos las adicciones como enfermedades de la mente potencialmente graves y que afectan a diversas áreas del funcionamiento de una persona. Las adicciones pueden afectar al estado de salud física, estado mental, vida familiar, vida en pareja y sentimental, rendimiento académico, trabajo, relaciones sociales, habilidades cognitivas, conducción, coordinación motora y vida espiritual.El uso excesivo de una sustancia adictiva (como pueda ser el tabaco, el alcohol, la cocaína o el cannabis) o de una actividad con riesgo de convertirse en adictiva (como el juego, el sexo o los videojuegos), puede potencialmente convertirse en una adicción. Aunque es controvertido establecer un límite entre el uso recreativo y el abuso, la presencia de problemas asociados al consumo nos delimita la frontera. Esos problemas suelen ser en el ámbito de la salud física (por ejemplo, afectación del hígado por el consumo de alcohol), la salud mental (alucinaciones con el consumo de cocaína), la situación económica (arruinarse jugando en un casino), el rendimiento académico (no estudiar los exámenes por pasar demasiadas horas jugando a videojuegos) o las relaciones sociales (no salir con los amigos por preferir fumar porros en la habitación).</p>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>

 <br> <br>

<?php include 'pie.php'; ?>
